#!/bin/bash
#setup_test_env

set -x -e

DEPLOYMENT_NAME="cephfs-bosh-release-standalone"
MOUNTPOINT_NAME="mountpoint"

### Install ruby and the the bosh cli
sudo apt-get update
sudo apt-get --assume-yes install build-essential expect ruby ruby-dev libxml2-dev libsqlite3-dev libxslt1-dev libpq-dev libmysqlclient-dev zlib1g-dev ceph-fuse
gem install bosh_cli --no-ri --no-rdoc

/usr/bin/expect <<EOD
spawn bosh logout
expect eof

spawn bosh target https://52.72.95.180:25555
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof

spawn bosh login
expect "Your username:"
send "admin\n"
expect "password:"
send "admin\n"
expect eof
EOD

echo "### Generate cephfs-bosh-release manifest"
wget https://github.com/cloudfoundry-incubator/spiff/releases/download/v1.0.7/spiff_linux_amd64
sudo chmod +x spiff_linux_amd64
sudo ln -s $(pwd)/spiff_linux_amd64 /usr/bin/spiff

pushd cephfs-bosh-release
echo "Generating Manifest"
ls
./templates/generate_manifest.sh aws ${DEPLOYMENT_NAME}
popd
eval `ssh-agent -s`
chmod 600 deployments-runtime/persi-ci/keys/bosh.pem
ssh-add deployments-runtime/persi-ci/keys/bosh.pem
cephfs_ip=$(bosh vms ${DEPLOYMENT_NAME} | grep 'cephfs/0' | awk '{print $11}')
mkdir /tmp/cephfs-files
pushd  /tmp/cephfs-files

echo "creating config files"
echo $cephfs_ip >  ip.conf

scp -o StrictHostKeyChecking=no vcap@$cephfs_ip:/etc/ceph/ceph.client.admin.keyring .
scp -o StrictHostKeyChecking=no vcap@$cephfs_ip:/etc/ceph/ceph.conf .

popd
mkdir /tmp/test
mkdir $MOUNTPOINT_NAME
#echo $(pwd)/$MOUNTPOINT_NAME >  /tmp/cephfs-files/mountpoint.conf
echo "/tmp/test" >  /tmp/cephfs-files/mountpoint.conf
cat /tmp/cephfs-files/mountpoint.conf
cat /tmp/cephfs-files/ip.conf
cat /tmp/cephfs-files/ceph.client.admin.keyring
export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH


cd diego-release
export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

# pwd
# ls
# echo ""
# echo "diego-release (branch: cf_persistence): submodule update volman"
# echo "---------------------------------------------------------------"
# #./scripts/update
# git submodule sync --recursive && git submodule foreach --recursive git submodule sync  && git submodule update --init --recursive
# git submodule update --remote --merge src/github.com/cloudfoundry-incubator/volman

# echo ""
# echo "diego-release (branch: cf_persistence): submodule update cephdriver"
# echo "---------------------------------------------------------------"
# git submodule update --remote --merge src/github.com/cloudfoundry-incubator/cephdriver



#go install github.com/apcera/gnatsd
#go install github.com/coreos/etcd
go get github.com/onsi/ginkgo/ginkgo
go get github.com/onsi/gomega
go install github.com/onsi/ginkgo/ginkgo
go install github.com/onsi/gomega

cd src/github.com/cloudfoundry-incubator/cephdriver
ginkgo -r -p
